package cauBlackHole.photoragephoto.domain

import cauBlackHole.photoragephoto.config.DynamoDBConfig
import com.amazonaws.services.dynamodbv2.datamodeling.*
import java.time.LocalDateTime

@DynamoDBTable(tableName = "Photo")
data class Photo (
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    var id: String? = null,

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "albumId-createdAt-index")
    var albumId: String,

    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "albumId-createdAt-index")
    @DynamoDBTypeConverted(converter = DynamoDBConfig.Companion.LocalDateTimeConverter::class)
    var createdAt: LocalDateTime,

    @DynamoDBAttribute
    var memberId: String,

    @DynamoDBAttribute
    var imageUrl: String,
)
